source 'https://rubygems.org'


gem 'rails', '4.1.4'
gem 'pg', '0.17.1'
gem 'devise', '3.2.4'
gem 'cancancan', '1.9.2'
gem 'sass-rails', '~> 4.0.3'
gem 'redis-rails', '4.0.0'
gem 'jbuilder', '~> 2.0'

group :development do 
	gem 'spring', '1.1.3'
	gem 'spring-commands-rspec', '1.0.2'
	gem 'thin', '1.6.2'
	#gem 'quiet_assets'
end



gem 'sdoc', '~> 0.4.0',          group: :doc