source 'https://rubygems.org'


gem 'rails', '4.1.4'
gem 'pg', '0.17.1'
gem 'devise', '3.2.4'
gem 'cancancan', '1.9.2'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'redis-rails', '4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'nokogiri', '1.6.1'
gem 'globalize'

group :development do
  gem 'spring', '1.1.3'
  gem 'spring-commands-rspec', '1.0.2'
  gem 'thin', '1.6.2'
  gem 'guard-livereload'
  gem 'quiet_assets'
  gem 'slim', '2.0.3'
  gem 'autoprefixer-rails', '2.2.0.20140804'
end

group :test, :development do
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'faker', '~> 1.4.2'
  gem 'konacha', '~> 3.2'
end

group :test do
#  gem 'capybara', '~> 2.3.0'
#  gem 'capybara-webkit', '~> 1.2.0'
  gem 'fabrication', '~> 2.11.3'
  gem 'launchy', '~> 2.4.2'
  gem 'simplecov', '~> 0.9.0', :require => false
end

group :production do
  gem 'rails_12factor'
end


gem 'sdoc', '~> 0.4.0',          group: :doc
