require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Publishers::TestsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Publishers::Test. As you add validations to Publishers::Test, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Publishers::TestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all publishers_tests as @publishers_tests" do
      test = Publishers::Test.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:publishers_tests)).to eq([test])
    end
  end

  describe "GET show" do
    it "assigns the requested publishers_test as @publishers_test" do
      test = Publishers::Test.create! valid_attributes
      get :show, {:id => test.to_param}, valid_session
      expect(assigns(:publishers_test)).to eq(test)
    end
  end

  describe "GET new" do
    it "assigns a new publishers_test as @publishers_test" do
      get :new, {}, valid_session
      expect(assigns(:publishers_test)).to be_a_new(Publishers::Test)
    end
  end

  describe "GET edit" do
    it "assigns the requested publishers_test as @publishers_test" do
      test = Publishers::Test.create! valid_attributes
      get :edit, {:id => test.to_param}, valid_session
      expect(assigns(:publishers_test)).to eq(test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Publishers::Test" do
        expect {
          post :create, {:publishers_test => valid_attributes}, valid_session
        }.to change(Publishers::Test, :count).by(1)
      end

      it "assigns a newly created publishers_test as @publishers_test" do
        post :create, {:publishers_test => valid_attributes}, valid_session
        expect(assigns(:publishers_test)).to be_a(Publishers::Test)
        expect(assigns(:publishers_test)).to be_persisted
      end

      it "redirects to the created publishers_test" do
        post :create, {:publishers_test => valid_attributes}, valid_session
        expect(response).to redirect_to(Publishers::Test.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publishers_test as @publishers_test" do
        post :create, {:publishers_test => invalid_attributes}, valid_session
        expect(assigns(:publishers_test)).to be_a_new(Publishers::Test)
      end

      it "re-renders the 'new' template" do
        post :create, {:publishers_test => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested publishers_test" do
        test = Publishers::Test.create! valid_attributes
        put :update, {:id => test.to_param, :publishers_test => new_attributes}, valid_session
        test.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested publishers_test as @publishers_test" do
        test = Publishers::Test.create! valid_attributes
        put :update, {:id => test.to_param, :publishers_test => valid_attributes}, valid_session
        expect(assigns(:publishers_test)).to eq(test)
      end

      it "redirects to the publishers_test" do
        test = Publishers::Test.create! valid_attributes
        put :update, {:id => test.to_param, :publishers_test => valid_attributes}, valid_session
        expect(response).to redirect_to(test)
      end
    end

    describe "with invalid params" do
      it "assigns the publishers_test as @publishers_test" do
        test = Publishers::Test.create! valid_attributes
        put :update, {:id => test.to_param, :publishers_test => invalid_attributes}, valid_session
        expect(assigns(:publishers_test)).to eq(test)
      end

      it "re-renders the 'edit' template" do
        test = Publishers::Test.create! valid_attributes
        put :update, {:id => test.to_param, :publishers_test => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publishers_test" do
      test = Publishers::Test.create! valid_attributes
      expect {
        delete :destroy, {:id => test.to_param}, valid_session
      }.to change(Publishers::Test, :count).by(-1)
    end

    it "redirects to the publishers_tests list" do
      test = Publishers::Test.create! valid_attributes
      delete :destroy, {:id => test.to_param}, valid_session
      expect(response).to redirect_to(publishers_tests_url)
    end
  end

end
